---
- name: Copy composer dockerfiles
  ansible.builtin.copy: 
    src: composer{{ item }}.dockerfile
    dest: "{{ DOCKER_ROOT_PATH }}/composer/dockerfile{{ item }}"
    force: yes
  with_items:
  - ['22_81', '26_83']

- name: Build composer images
  community.docker.docker_image: 
    name: awsb_composer
    tag: "{{ item }}"
    build: 
      path: "{{ DOCKER_ROOT_PATH }}/composer"
      dockerfile: "dockerfile{{ item }}"
      nocache: yes
    force_source: yes
    source: build
  with_items:
  - ['22_81', '26_83']